---
mountPath: "hub"
mountRole: "hub-role"

caProvider:
  enabled: true
  hubCluster:
    type: ConfigMap
    name: kube-root-ca.crt
    key: ca.crt
    namespace: golang-external-secrets
  nonhubCluster:
    type: Secret
    name: hub-ca
    key: hub-kube-root-ca.crt
    namespace: imperative

global:
  hubClusterDomain: hub.example.com
  clusterDomain: foo.example.com

clusterGroup:
  isHubCluster: true

external-secrets:
  image:
    tag: v0.9.8-ubi
  webhook:
    image:
      tag: v0.9.8-ubi
  certController:
    image:
      tag: v0.9.8-ubi
