apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true, Validate=false, SkipDryRunOnMissingResource=true
spec:
  servingCerts:
    namedCertificates:
      - names:
        - api.{{ $.Values.global.clusterDomain }}
        servingCertificate:
          name: api-cert
