---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vp-ca-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vp-selfsigned-ca
spec:
  isCA: true
  commonName: validatedpatterns-selfsigned-ca
  secretName: vp-ca-root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: vp-ca-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vp-ca-issuer
spec:
  ca:
    secretName: localhost-serving-signer
    #secretNamespace: cert-manager-operator
