---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true, Validate=false, SkipDryRunOnMissingResource=true
spec:
  routeAdmission:
    wildcardPolicy: WildcardsAllowed
  defaultCertificate:
    name: ingress-cert
