# See https://github.com/external-secrets/external-secrets-helm-operator/blob/main/config/samples/operator_v1alpha1_operatorconfig.yaml
# for a full definition
apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  name: golang-external-secrets
spec:
  image:
    tag: {{ .Values.image.tag }}
  webhook:
    image:
      tag: {{ .Values.webhook.image.tag }}
  certController:
    image:
      tag: {{ .Values.certController.image.tag }}
  prometheus:
    enabled: true
    service:
      port: 8080
  resources:
    requests:
      cpu: 10m
      memory: 96Mi
    limits:
      cpu: 100m
      memory: 256Mi
