---
apiVersion: v1
kind: Secret
metadata:
  name: golang-external-secrets
  namespace: golang-external-secrets
  annotations:
    kubernetes.io/service-account.name: golang-external-secrets
    # This is because we need to deploy the secret *after* the operatorconfig has created the
    # golang-external-secret service account
    argocd.argoproj.io/sync-wave: "10"
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: golang-external-secrets
  namespace: golang-external-secrets
