# Generated by patternizer
# This Makefile includes the common pattern targets from Makefile-common
# You can add custom targets above or below the include line

include Makefile-common
.PHONY: help

.PHONY: cert-test
cert-test: ## silly test to reuse the existing API CA in cert-manager
	oc new-project cert-manager
	oc get -n openshift-kube-apiserver-operator secrets/localhost-serving-signer --namespace=openshift-kube-apiserver-operator  -o yaml |  grep -v '^\s*namespace:\s'  | oc apply --namespace=cert-manager -f -
