---
global:
  pattern: multicloud-gitops
  singleArgoCD: false
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
main:
  variant: hub
  patternsOperator:
    enableSubscription: false
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: "0.9.*"
