clusterGroup:
  name: hub
  isHubCluster: true
  namespaces:
    - openshift-serverless:
        operatorGroup: true
        targetNamespaces: []
    - openshift-nfd
    - nvidia-gpu-operator
    - redhat-ods-operator:
        operatorGroup: true
        targetNamespaces: []
    - vault
    - golang-external-secrets
    - minio-ns
    - demo-ds-project:
        annotations:
          openshift.io/description: 'Demo DS Workspace'
          openshift.io/display-name: 'Demo DS Workspace'
        labels:
          kubernetes.io/metadata.name: "demo"
          modelmesh-enabled: 'false'
          opendatahub.io/dashboard: 'true'
  subscriptions:
    serverless:
      name: serverless-operator
      namespace: openshift-serverless
      channel: stable
    servicemesh:
      name: servicemeshoperator
      namespace: openshift-operators
      channel: stable
    nfd:
      name: nfd
      namespace: openshift-nfd
      channel: stable
    nvidia:
      name: gpu-operator-certified
      namespace: nvidia-gpu-operator
      channel: v24.6
      source: certified-operators
    authorino:
      name: authorino-operator
      namespace: openshift-operators
      channel: tech-preview-v1
      source: redhat-operators
      sourceNamespace: openshift-marketplace
    rhoai:
      name: rhods-operator
      namespace: redhat-ods-operator
      channel: alpha
      source: redhat-operators
      sourceNamespace: openshift-marketplace
  projects:
    - hub
    - openshift-ai
    - s3
    - ds-projects
  applications:
    vault:
      name: vault
      namespace: vault
      project: hub
      chart: hashicorp-vault
      chartVersion: 0.1.*
    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: hub
      chart: golang-external-secrets
      chartVersion: 0.1.*
    nfd-config:
      name: nfd-config
      namespace: openshift-nfd
      project: openshift-ai
      path: charts/all/nfd-config
    nvidia-config:
      name: nvidia-config
      namespace: nvidia-gpu-operator
      project: openshift-ai
      path: charts/all/nvidia-config
    rhoai-config:
      name: rhoai-config
      namespace: redhat-ods-operator
      project: openshift-ai
      path: charts/all/rhoai-config
    minio:
      name: minio
      namespace: minio-ns
      project: s3
      path: charts/all/minio
    ds-project:
      name: ds-project
      namespace: demo-ds-project
      project: ds-projects
      path: charts/all/ds-project

vars:
  minio:
    bucket_name: localdocs