---
global:
  pattern: multicloud-gitops
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
main:
  clusterGroupName: standalone
  multiSourceConfig:
    enabled: true
    # clusterGroupChartVersion: "0.9.*"
    clusterGroupGitRepoUrl: https://github.com/mbaldessari/clustergroup-chart
    clusterGroupChartGitRevision: vault_jwt_tag
