apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: broker
  namespace: broker
spec:
  acceptors:
    - expose: true
      name: mqtt
      port: {{ .Values.broker.port }}
      protocols: mqtt
  # FIXME(bandini): use ESO
  adminPassword: admin
  adminUser: admin
  deploymentPlan:
    image: placeholder
    jolokiaAgentEnabled: false
    journalType: nio
    managementRBACEnabled: true
    messageMigration: false
    persistenceEnabled: false
    requireLogin: false
    size: 1
