apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: template
spec:
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    template:
      data:
        adminPassword: |-
          {{ "{{ .adminpassword | toString }}" }}
  data:
  - secretKey: adminpassword
    remoteRef:
      key: "secret/data/global/amq"
      property: amqpassword
