apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: template
spec:
  target:
    template:
      mergePolicy: Merge
      engineVersion: v2
      data:
        apiVersion: broker.amq.io/v1beta1
        kind: ActiveMQArtemis
        metadata:
          name: broker
          namespace: broker
        spec:
          acceptors:
            - expose: true
              name: mqtt
              port: 1883
              protocols: mqtt
          adminPassword: {{ "{{ .adminpassword | toString }}" }}
          adminUser: admin
          deploymentPlan:
            image: placeholder
            jolokiaAgentEnabled: false
            journalType: nio
            managementRBACEnabled: true
            messageMigration: false
            persistenceEnabled: false
            requireLogin: false
            size: 1
  data:
  - secretKey: adminpassword
    remoteRef:
      key: /secrets/data/global/amq
      property: amqpassword
