---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: developerhub-link
spec:
  applicationMenu:
    section: DeveloperHub
  href: 'https://backstage-developer-hub-{{ .Values.developerhub.namespace }}.apps.{{ .global.clusterDomain }}'
  location: ApplicationMenu
  text: 'DeveloperHub with AI templates'