---
apiVersion: v1
kind: Secret
metadata:
  name: rhdh-token-secret
  annotations:
    kubernetes.io/service-account.name: "rhdh-k8s-sa"
type: kubernetes.io/service-account-token
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-secret-tekton
spec:
  data:
    - conversionStrategy: None
      match:
        remoteRef:
          remoteKey: pushsecrets/rhdh-tekton-keys
          property: RHDH_TEKTON_SERVICE_ACCOUNT_TOKEN
        secretKey: token
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
  - name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  selector:
    secret:
      name: rhdh-token-secret
  updatePolicy: Replace
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: rhdh-tekton-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: rhdh-tekton-secret
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: secret/data/pushsecrets/rhdh-tekton-keys