---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-secret-argo
  namespace: {{ $ns }}
spec:
  data:
    - conversionStrategy: None
      match:
        remoteRef:
          remoteKey: pushsecrets/rhdh-argo-keys
          property: ARGOCD_PASSWORD
        secretKey: admin.password
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
  - name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  selector:
    secret:
      name: {{ $.Values.clusterGroup.name }}-gitops-cluster
  updatePolicy: Replace
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: rhdh-argo-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: rhdh-argo-secret
    template:
      type: Opaque
      engineVersion: v2
      metadata:
      data: |
        ARGOCD_USERNAME: admin
        ARGOCD_PASSWORD: {{ `{{ .argocd_pass }}` }}
  data:
  - secretKey: argocd_pass
    remoteRef:
      key: "pushsecrets/rhdh-argo-keys"
      property: "ARGOCD_PASSWORD"