---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: db-external-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: db-secret
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.dbsecret.key }}