kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.database.name }}
spec:
  ports:
    - name: mariadb
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: {{ .Values.database.name }}