apiVersion: v1
kind: ConfigMap
metadata:
  name: mssql-pull-secret-tpl
data:
  .dockerconfigjson: |
     {
       "auths": 
         {
          "{{ .Values.image.registry }}": 
            {
              "username": "{{ `{{ .registry_username }}` }}",
              "password": "{{ `{{ .registry_password }}` }}",
              "auth": "{{ `{{ .registry_username }}:{{ .registry_password }} ` }}"
            }
         }
     }
