apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: mssql-pull-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: mssql-pull-secret
    template:
      type: Opaque
      engineVersion: v2
      stringData:
        .dockerconfigjson: |-
         {
           "auths": 
             {
              "{{ .Values.image.registry }}": 
                {
                  "username": "{{ `{{ .registry_username }}` }}",
                  "password": "{{ `{{ .registry_password }}` }}",
                  "auth": "{{ `{{ .registry_username }}:{{ .registry_password }} | b64enc` }}"
                }
             }
         }
  data:
  - secretKey: registry_username
    remoteRef:
      key: "global/mssql"
      property: "username"
  - secretKey: registry_password
    remoteRef:
      key: "global/mssql"
      property: "password"
