apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: mssql-pull-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: mssql-pull-secret
    template:
      type: Opaque
      engineVersion: v2
      templateFrom:
      - target: Data
        configMap:
          name: mssql-pull-secret-tpl
          items:
          - key: .dockercfg
            templateAs: Values
  data:
  - secretKey: dockerauth
    remoteRef:
      key: "global/mssql"
      property: "dockerauth"
  - secretKey: dockeruser
    remoteRef:
      key: "global/mssql"
      property: "dockeruser"
  - secretKey: dockerpass
    remoteRef:
      key: "global/mssql"
      property: "dockerpass"
